trigger:
  batch: true
  branches:
    include:
    - main
    - release/*
  paths:
    exclude:
    - docs/*

pr: none

variables:
- template: /eng/pipelines/common-variables.yml@self

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      credscan:
        suppressionsFile: $(Build.SourcesDirectory)\.config\CredScanSuppressions.json
      sourceAnalysisPool:
        name: NetCore1ESPool-Svc-Internal
        image: 1es-windows-2022
        os: windows
    stages:
    - stage: build
      displayName: Build
      jobs:
      - template: /eng/common/templates-official/jobs/jobs.yml@self
        parameters:
          artifacts:
            publish:
              artifacts: true
              logs: true
              manifests: true
          enableMicrobuild: true
          enablePublishUsingPipelines: true
          jobs:
          - job: Windows_NT
            timeoutInMinutes: 90
            pool:
              name: NetCore1ESPool-Svc-Internal
              image: windows.vs2022.amd64
              os: windows
            steps:
            - script: eng\common\cibuild.cmd
                -configuration $(_BuildConfig)
                -prepareMachine
                $(_InternalBuildArgs)
              displayName: Windows Build / Publish

    - template: /eng/common/templates-official/post-build/post-build.yml@self
      parameters:
        enableSourceLinkValidation: false
        enableSigningValidation: false
        symbolPublishingAdditionalParameters: /p:PublishToSymWeb=false /p:PublishToMSDL=false
